name: Titanic Model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd titanic_model
          pip install -r requirements.txt
          python wrangle.py
          python train_pipeline.py
          python predict.py

          echo "## Model metrics" > report.md
          cat trained_model_artifacts/metrics_0.0.0.txt >> report.md

          echo "## Confusion Matrix" >> report.md
          cml-publish trained_model_artifacts/confustion_matrix_v0.0.0.png --md >> report.md
          cml-publish trained_model_artifacts/normalized_confustion_matrix_v0.0.0.png --md >> report.md

          cml-send-comment report.md
