name: Titanic Model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install tox
          tox      
          echo "## Model metrics" > report.md
          cat titanic_model/trained_model_artifacts/metrics_0.0.0.txt >> report.md

          echo "## Confusion Matrix" >> report.md
          cml-publish titanic_model/trained_model_artifacts/confustion_matrix_v0.0.0.png --md >> report.md
          cml-publish titanic_model/trained_model_artifacts/normalized_confustion_matrix_v0.0.0.png --md >> report.md

          cml-send-comment report.md
