name: Titanic Model - train & test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Installing DVC"
          sudo -H pip install dvc[s3]
          echo "Installing tox"
          sudo -H pip install tox
          echo "DVC pulling data"
          dvc pull

          export VERSION=$(head titanic_model/VERSION)
          echo "## Model Version - $VERSION" > reports.md
          tox
          echo "## Model metrics" >> report.md
          cat titanic_model/trained_model_artifacts/metrics_$VERSION.txt >> report.md

          echo "## Confusion Matrix" >> report.md
          cml-publish titanic_model/trained_model_artifacts/confustion_matrix_v$VERSION.png --md >> report.md
          cml-publish titanic_model/trained_model_artifacts/normalized_confustion_matrix_v$VERSION.png --md >> report.md

          cml-send-comment report.md
