name: Titanic Model - train & test
on:
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          printenv

          echo 'HI CML' > report.md
          cml-send-comment report.md
