name: Titanic Model
on: [push, pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export VERSION=$(head titanic_model/VERSION)
          echo "## Model Version - $VERSION"
          sudo -H pip install tox
          tox      
          echo "## Model metrics" > report.md
          cat titanic_model/trained_model_artifacts/metrics_$VERSION.txt >> report.md

          echo "## Confusion Matrix" >> report.md
          cml-publish titanic_model/trained_model_artifacts/confustion_matrix_v$VERSION.png --md >> report.md
          cml-publish titanic_model/trained_model_artifacts/normalized_confustion_matrix_v$VERSION.png --md >> report.md

          cml-send-comment report.md
